language: node_js
node_js:
  - 'stable'
services:
  - mysql
addons:
  apt:
    packages:
      - sshpass
before_install:
  - mysql -u root -e 'CREATE DATABASE IF NOT EXISTS ooly_test;'
env:
  - NODE_ENV=test
after_success:
  - export SSHPASS=$DEPLOY_PASS
  - sshpass -e ssh $DEPLOY_USER@$DEPLOY_HOST api/deploy_develop.sh
