language: node_js
node_js:
  - stable
addons:
  mariadb: 10.5
  apt:
    packages:
      - sshpass
before_install:
  - sudo mysql -u root -e 'CREATE DATABASE IF NOT EXISTS ooly_test;'
  - sudo mysql -e "SET Password=PASSWORD('travis')"
env:
  - NODE_ENV=test
after_success:
  - export SSHPASS=$DEPLOY_PASS
  - test $TRAVIS_BRANCH = "develop" && sshpass -e ssh $DEPLOY_USER@$DEPLOY_HOST -o stricthostkeychecking=no 'bash ./deploy_api_develop.sh'
  - test $TRAVIS_BRANCH = "master" && sshpass -e ssh $DEPLOY_USER@$DEPLOY_HOST -o stricthostkeychecking=no 'bash ./deploy_api_master.sh'
