version: '3'
services:
  db:
    build: ./
    container_name: ooly_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    volumes:
      - ./_docker/mariadb/init:/docker-entrypoint-initdb.d
    networks:
      vpcbr:
        ipv4_address: 172.168.0.2
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ooly_phpmyadmin
    ports:
      - 1234:80
    links:
      - db:db
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      vpcbr:
        ipv4_address: 172.168.0.3
  redis:
    image: redis
    container_name: ooly_redis
    ports:
      - 6379:6379
    networks:
      vpcbr:
        ipv4_address: 172.168.0.4
networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 172.168.0.0/16
