module.exports = [
  {
    uuid: '1c115903-1aa5-4216-b438-5e455124f66d',
    name: "Disc'Oo",
    description:
      'Disc’Oo adore la musique. Il est super calé, il connait pleins d’artistes différents et il aime tous les styles. Parfois d’humeur à réécouter les classiques et parfois voulant plutôt découvrir de nouveaux morceaux, Disc’Oo trouve toujours une musique à écouter et à partager. C’est d’ailleurs très important pour lui, de partager. Il adore créer une bonne ambiance pour tous ceux qui l’accompagnent.',
    color: '#1500db',
    objectName: 'Disc_Oo',
    toreObjectName: 'Tore_3',
    isAvailable: true,
    entries: ['EntreeDisco_1.mp3', 'EntreeDisco_2.mp3', 'EntreeDisco_3.mp3'],
    exits: ['SortieDisco_1.mp3', 'SortieDisco_2.mp3', 'SortieDisco_3.mp3'],
    hellos: ['BonjourDisco_1.mp3', 'BonjourDisco_2.mp3', 'BonjourDisco_3.mp3'],
    byes: ['AuRevoirDisco_1.mp3', 'AuRevoirDisco_2.mp3', 'AuRevoirDisco_3.mp3'],
    noScenario: ['NoScenarioDisco_1.mp3'],
  },
  {
    uuid: '23c7e653-f1a6-435c-9f58-24f9efb8c5e1',
    name: "Cin'Oo'che",
    description:
      'Le truc de Cin’Oo’che, c’est le cinéma et les séries. Il en a vu un paquet et de tous les genres, comiques, épiques, animation, horreur, romantiques, etc. Le 7eme art n’a pas de secret pour lui. Il en connait un rayon sur les acteurs, les réalisateurs, les effets spéciaux. Mais ce qu’il aime le plus, c’est les textes, les répliques de films cultes, les dialogues alambiqués, les citations qui parlent à tout le monde, les références qu’il est le seul à connaitre. Il a une super mémoire Cin’Oo’che, donc les répliques, il les apprend vite, et il adore les partager avec les autres.',
    color: '#CA0024',
    objectName: 'Cinoche_1',
    toreObjectName: 'Tore_5',
    isAvailable: true,
    entries: ['EntreeCinoche_1.mp3', 'EntreeCinoche_2.mp3', 'EntreeCinoche_3.mp3'],
    exits: ['SortieCinoche_1.mp3', 'SortieCinoche_2.mp3', 'SortieCinoche_3.mp3'],
    hellos: ['EntreeCinoche_1.mp3', 'EntreeCinoche_2.mp3', 'EntreeCinoche_3.mp3'],
    byes: ['AuRevoirCinoche_1.mp3', 'AuRevoirCinoche_2.mp3', 'AuRevoirCinoche_3.mp3'],
    noScenario: ['NoScenarioCinooche_1.mp3'],
  },
  {
    uuid: '4d8cf885-f681-452f-97a6-5077744eb4be',
    name: "Inf'Oo",
    description:
      'Inf’Oo en connait un rayon sur les faits rigolos et surprenants qui agrémentent la vie, et ce dans tous les domaines : la culture, l’histoire, la biologie, etc. Ça lui fait beaucoup d’histoires à raconter. Il se tient aussi toujours au courant des dernières nouvelles, pour continuer d’apprendre et de raconter. Il adore discuter avec tous les autres Oo et leur poser des questions, car ils connaissent tous pleins d’anecdotes dans des domaines différents, du coup, il peut apprendre pleins de choses et partager ses propres informations.',
    color: '#24709c',
    objectName: 'Infoo',
    toreObjectName: 'Tore_8',
    isAvailable: true,
    entries: ['EntreeInfo_1.mp3', 'EntreeInfo_2.mp3', 'EntreeInfo_3.mp3'],
    exits: ['SortieInfo_1.mp3', 'SortieInfo_2.mp3', 'SortieInfo_3.mp3'],
    hellos: ['BonjourInfo_1.mp3', 'BonjourInfo_2.mp3', 'BonjourInfo_3.mp3'],
    byes: ['AuRevoirInfo_1.mp3', 'AuRevoirInfo_2.mp3', 'AuRevoirInfo_3.mp3'],
    noScenario: ['NoScenarioInfo_1.mp3'],
  },
  {
    uuid: 'a10058d0-46e0-4e54-bf54-72bef1ae283f',
    name: "Y'Oo'ga",
    description:
      'Y’Oo’ga est le plus calme des Oo. Il connaît plein d’exercices de relaxation et de détente. Passionné de méditation, de Taï-chï et de sophrologie, Y’Oo’ga est toujours présent pour proposer des occupations relaxantes. Quand il est là, il instaure une ambiance calme qui plaît aux autres Oo pendant la nuit.',
    color: '#37826b',
    objectName: 'Yoga',
    toreObjectName: 'Tore_1',
    isAvailable: true,
    entries: ['EntreeYoga_1.mp3', 'EntreeYoga_2.mp3', 'EntreeYoga_3.mp3'],
    exits: ['SortieYoga_1.mp3', 'SortieYoga_2.mp3', 'SortieYoga_3.mp3'],
    hellos: ['BonjourYoga_1.mp3', 'BonjourYoga_2.mp3', 'BonjourYoga_3.mp3'],
    byes: ['AuRevoirYoga_1.mp3', 'AuRevoirYoga_2.mp3', 'AuRevoirYoga_3.mp3'],
    noScenario: ['NoScenarioYoga_1.mp3'],
  },
  {
    uuid: 'ca5f71b5-8dc0-4acd-9d58-3c3035622afe',
    name: "Végét'Oo",
    description:
      'La passion de Végét’Oo, c’est les plantes. Il est fasciné par cette vie à la fois si délicate et si complexe. C’est vrai que certaines utilisent des mécanismes assez étonnants pour survivre. Que ce soit les plantes d’Europe, d’Amérique, d’Asie, d’Afrique ou d’Océanie, Végét’Oo les découvre toutes avec autant de joie. Grâce à elles, il fait le tour du monde sans quitter la tribu.',
    color: '#1b3619',
    objectName: 'Vegeto_1',
    toreObjectName: 'Tore_4',
    isAvailable: true,
    entries: ['EntreeVegeto_1.mp3', 'EntreeVegeto_2.mp3', 'EntreeVegeto_3.mp3'],
    exits: ['SortieVegeto_1.mp3', 'SortieVegeto_2.mp3', 'SortieVegeto_3.mp3'],
    hellos: ['BonjourVegeto_1.mp3', 'BonjourVegeto_2.mp3', 'BonjourVegeto_3.mp3'],
    byes: ['AuRevoirVegeto_1.mp3', 'AuRevoirVegeto_2.mp3', 'AuRevoirVegeto_3.mp3'],
    noScenario: ['NoScenarioVegeto_1.mp3'],
  },
  {
    uuid: '92021a2e-77d3-48b6-bd31-3e86d6792e05',
    name: "Wh'Oo'w",
    description:
      'Wh’Oo’w est un Oo plein de surprises, avec lui, on ne sait jamais à quoi s’attendre ! Il apporte un peu de piment dans les discussions et occupations de ses compagnons, en leur proposant d’ajouter un peu de hasard et de surprise dans ce qu’ils font. Que ce soit en s’inspirant d’un mot pris au hasard dans le dictionnaire, ou en faisant des choix à pile ou face, avec lui, les situations deviennent toujours un peu décalées et étonnantes !',
    color: '#FFB300',
    objectName: 'Whow_1',
    toreObjectName: 'Tore_7',
    isAvailable: true,
    entries: ['EntreeWhow_1.mp3', 'EntreeWhow_2.mp3', 'EntreeWhow_3.mp3'],
    exits: ['SortieWhow_1.mp3', 'SortieWhow_2.mp3', 'SortieWhow_3.mp3'],
    hellos: ['BonjourWhow_1.mp3', 'BonjourWhow_2.mp3', 'BonjourWhow_3.mp3'],
    byes: ['AuRevoirWhow_1.mp3', 'AuRevoirWhow_2.mp3', 'AuRevoirWhow_3.mp3'],
    noScenario: ['NoScenarioWhoo_1.mp3'],
  },
  {
    uuid: '55a7bed3-a9a5-4c6c-9913-d8966d8dfc59',
    name: "C'Oo'mique",
    description:
      'C’Oo’mique est le roi des plaisanteries. Il a un humour un peu potache et décalé et il adore les blagues, les charades, les devinettes et les jeux de mot. Il en connait des classiques, mais il essaie aussi d’en inventer lui-même. D’ailleurs ce qu’il préfère, c’est trouver des plaisanteries en lien avec ce que disent ses compagnons Oo.',
    color: '#FFE92D',
    objectName: 'Comique_1',
    toreObjectName: 'Tore_6',
    isAvailable: true,
    entries: ['EntreeComique_1.mp3', 'EntreeComique_2.mp3', 'EntreeComique_3.mp3'],
    exits: ['SortieComique_1.mp3', 'SortieComique_2.mp3', 'SortieComique_3.mp3'],
    hellos: ['BonjourComique_1.mp3', 'BonjourComique_2.mp3', 'BonjourComique_3.mp3'],
    byes: ['AuRevoirComique_1.mp3', 'AuRevoirComique_2.mp3', 'AuRevoirComique_3.mp3'],
    noScenario: ['NoScenarioComique_1.mp3'],
  },
  {
    uuid: '1fd0f001-5950-4f22-983d-11d08cee3add',
    name: "Méli-Mél'Oo",
    description:
      'Méli-Mél’Oo s’emmèle toujours les pinceaux, c’est un peu le prince des gaffes. S’il avait des mains, il aurait sans doute “deux mains gauches”. Il mélange parfois les mots ou bien les expressions. Malgré tout, Méli-mél’Oo est toujours gentil et attentif avec ses compagnons, il essaie d’apprendre leur spécialité, de les aider quand ils en ont besoin. Et tout le monde lui pardonne ses petites maladresses, qui au final sont plutot amusantes.',
    color: '#5b32a8',
    objectName: 'melimelo_1',
    toreObjectName: 'Tore_2',
    isAvailable: true,
    entries: ['BonjourMelimelo_1.mp3', 'BonjourMelimelo_2.mp3', 'BonjourMelimelo_3.mp3'],
    exits: ['SortieMelimelo_1.mp3', 'SortieMelimelo_2.mp3', 'SortieMelimelo_3.mp3'],
    hellos: ['BonjourMelimelo_1.mp3', 'BonjourMelimelo_2.mp3', 'BonjourMelimelo_3.mp3'],
    byes: ['AuRevoirMelimelo_1.mp3', 'AuRevoirMelimelo_2.mp3', 'AuRevoirMelimelo_3.mp3'],
    noScenario: ['NoScenarioMeliMeloo_1.mp3'],
  },
]
